# Generated by Django 5.0.3 on 2024-03-28 05:10

from wallet_manager.regexp_validators import PhoneNumberValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_manager', '0004_activitytracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[PhoneNumberValidator.validate_phone_number]),
        ),
    ]
