# Generated by Django 5.0.3 on 2024-03-28 05:13

from wallet_manager.regexp_validators import NameValidator, PhoneNumberValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_manager', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[NameValidator.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[NameValidator.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[PhoneNumberValidator.validate_phone_number]),
        ),
    ]
